"""migrate-again

Revision ID: 0b1fa044fb43
Revises: 66ea35490d30
Create Date: 2023-07-03 06:32:07.536609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1fa044fb43'
down_revision = '66ea35490d30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
