"""add analytics fields to click

Revision ID: f3a81f2310ab
Revises: a1b2c3d4e5f6
Create Date: 2026-05-27 05:04:25.537242

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = "f3a81f2310ab"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "click",
        sa.Column(
            "browser",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
            server_default="unknown",
        ),
    )
    op.add_column(
        "click",
        sa.Column(
            "os",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
            server_default="unknown",
        ),
    )
    op.add_column(
        "click",
        sa.Column(
            "referer",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
            server_default="(direct)",
        ),
    )
    op.add_column(
        "click",
        sa.Column(
            "utm_source", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "click",
        sa.Column(
            "utm_medium", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "click",
        sa.Column(
            "utm_campaign", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "click",
        sa.Column(
            "utm_term", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "click",
        sa.Column(
            "utm_content", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.create_index(
        "ix_click_country", "click", ["country_code", "created_at"], unique=False
    )
    op.create_index("ix_click_device", "click", ["device", "created_at"], unique=False)
    op.create_index(
        "ix_click_link_created", "click", ["link_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_click_referer", "click", ["referer", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_click_referer", table_name="click")
    op.drop_index("ix_click_link_created", table_name="click")
    op.drop_index("ix_click_device", table_name="click")
    op.drop_index("ix_click_country", table_name="click")
    op.drop_column("click", "utm_content")
    op.drop_column("click", "utm_term")
    op.drop_column("click", "utm_campaign")
    op.drop_column("click", "utm_medium")
    op.drop_column("click", "utm_source")
    op.drop_column("click", "referer")
    op.drop_column("click", "os")
    op.drop_column("click", "browser")
    # ### end Alembic commands ###
